---
- name: ensure motion packages are installed
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - motion
    - ffmpeg

- name: create folder for motion created files
  file:
    path: /var/motion
    state: directory
    owner: motion
    group: motion
    mode: 0750

- name: load module for pi camera
  command: modprobe bcm2835-v4l2
  notify:
    - restart motion

- name: permanent load module for pi camera
  lineinfile:
    dest: /etc/modules
    line: 'bcm2835-v4l2'
    insertbefore: EOF
    state: present

- name: copy mask.pgm file
  copy:
    src: "{{ motion_mask_file }}"
    dest: /etc/motion/mask.pgm
    owner: root
    group: motion
    mode: 0644
  when: motion_mask_file is defined
  notify:
    - restart motion
  tags:
    - conf

- name: configure motion
  template:
    src: etc/motion/motion.conf.j2
    dest: /etc/motion/motion.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart motion
  tags:
    - conf

- name: configure motion event scripts
  template:
    src: usr/local/bin/{{ item }}.j2
    dest: /usr/local/bin/{{ item }}
    owner: root
    group: motion
    mode: 0750
  with_items:
    - motionpushover
    - motionupload
  tags:
    - conf

- name: configure cron for motion
  copy:
    src: etc/cron.d/{{ item }}
    dest: /etc/cron.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - motionrestart
  tags:
    - conf

- name: autostart motion deamon
  replace:
    dest: /etc/default/motion
    regexp: '^start_motion_daemon=no'
    replace: 'start_motion_daemon=yes'

- name: ensure all motion services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - motion
