---
- name: configure apt
  template:
    src: etc/apt/sources_{{ ansible_distribution_release }}.list.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  register: sources

- name: update the package list
  apt: update_cache=yes
  when: sources.changed
