---
- name: ensure dnsmasq packages are installed
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - dnsmasq

- name: unlock resolve.conf
  command: chattr -i /etc/resolv.conf
  changed_when: False

- name: setup resolve.conf 1
  lineinfile:
    dest: /etc/resolv.conf
    line: "nameserver {{ ansible_default_ipv4.gateway}}"
    insertbefore: BOF
    state: present

- name: setup resolve.conf 2
  lineinfile:
    dest: /etc/resolv.conf
    line: "nameserver 127.0.0.1"
    insertbefore: BOF
    state: present

- name: lock resolve.conf
  command: chattr +i /etc/resolv.conf
  changed_when: False

- name: configure dnsmasq
  template:
    src: etc/dnsmasq.d/local.conf.j2
    dest: /etc/dnsmasq.d/local.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart dnsmasq

- name: ensure all dnsmasq services are started and enabled
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - dnsmasq

